<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>AstralChorus.Sim</AssemblyName>
    <RootNamespace>AstralChorus.Sim</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <ProjectReference Include="../AstralChorus.Logic/AstralChorus.Logic.csproj" />
  </ItemGroup>

</Project>
